# Generated by Django 5.0.7 on 2024-09-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noteapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="title",
            field=models.CharField(default="No Title", max_length=200),
        ),
    ]
