# Generated by Django 5.0.7 on 2024-09-10 02:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("noteapp", "0002_note_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="title",
        ),
    ]
